"""Checks package. Importing modules here registers them in the registry."""
from . import network          # noqa: F401
from . import site             # noqa: F401
from . import system           # noqa: F401
from . import capture          # noqa: F401
from . import server_security  # noqa: F401
from . import sqli             # noqa: F401
from . import cve_audit        # noqa: F401
from . import lynis_audit      # noqa: F401
from . import dns_audit        # noqa: F401
from . import breach_check     # noqa: F401
from . import cert_transparency  # noqa: F401
from . import rootkit_check    # noqa: F401
from . import aide_check       # noqa: F401
from . import backup_check     # noqa: F401
from . import docker_audit     # noqa: F401
from . import systemd_hardening  # noqa: F401
from . import nginx_hardening  # noqa: F401
from . import ssh_hardening    # noqa: F401
